Retrying after interrupts in store pops a bug in derbyall/storeall/storeunit/T_RawStoreFactory in some cases    Cf Myrna's comment on DERBY-4741:'I think the latest check-in has caused the following tinderbox failure:derbyall/storeall/storeall.fail:unit/T_RawStoreFactory.unitsee: http://dbtg.foundry.sun.com/derby/test/tinderbox_trunk16/jvm1.6/testing/testlog/SunOS-5.10_i86pc-i386/1061516-derbyall_diff.txt:                 Diff file derbyall/storeall/storeunit/T_RawStoreFactory.diff             Start: T_RawStoreFactory jdk1.6.0_18 storeall:storeunit 2011-01-20 23:22:23 ***2 del&lt; &#8211; Unit Test T_RawStoreFactory finished2 add&gt; ran out of time&gt; Exit due to time bombTest Failed. End: T_RawStoreFactory jdk1.6.0_18 storeall:storeunit 2011-01-21 00:22:54 ***'It failed in the nightly runs with ibm 1.6 also (and 1.4.2 and 1.5).   