<title>Issue 29400 -   chromium -    Exception in WebKit tests runner - Project Hosting on Google Code</title> <pre> yurys@yurys-win7 /cygdrive/d/chrome-git/src/webkit/tools/layout_tests  $ ../../../third_party/python_24/python.exe run_webkit_tests.py --noshow-  result  s --verbose --full-results-html --clobber-old-results   LayoutTests/plugins/embed  -attributes-setting.html  091204 14:00:54 run_webkit_tests.py:1240 INFO Running 16 test_shells in   parallel    091204 14:00:54 run_webkit_tests.py:1249 INFO Regular timeout: 6000  slow   test t  imeout: 30000  091204 14:00:54 run_webkit_tests.py:174 INFO Found: 1 tests  091204 14:00:55 run_webkit_tests.py:300 INFO Run: 1 tests  Traceback (most recent call last):    File &quot;run_webkit_tests.py&quot;  line 1453  in ?      main(options  args)    File &quot;run_webkit_tests.py&quot;  line 1281  in main      result_summary = test_runner.PrepareListsAndPrintOutput()    File &quot;run_webkit_tests.py&quot;  line 303  in PrepareListsAndPrintOutput      self._test_files | skip_chunk)  TypeError: unsupported operand type(s) for |: 'set' and 'tuple'  091204 14:00:55 run_webkit_tests.py:157 INFO flushing stdout  091204 14:00:55 run_webkit_tests.py:159 INFO flushing stderr  091204 14:00:55 run_webkit_tests.py:161 INFO stopping http server    yurys@yurys-win7 /cygdrive/d/chrome-git/src/webkit/tools/layout_tests  $ </pre>