<title>Issue 29727 -   chromium -    rebaseline tool gives error backtrace instead of error message - Project Hosting on Google Code</title> <pre> Enter a malformed item in the test_expectations file:    BUG REBASELINE MAC : LayoutTests/fast/workers/foobar    note that it doesn't have a &quot;= FAIL&quot; suffix on that line.    Now run the rebaseline tool. instead of getting a reasonable error message  you get an   exception thrown which is a pain to figure out.    Traceback (most recent call last):    File &quot;./webkit/tools/layout_tests/rebaseline.py&quot;  line 1018  in &lt;module&gt;      main()    File &quot;./webkit/tools/layout_tests/rebaseline.py&quot;  line 992  in main      rebaseliner = Rebaseliner(platform  options)    File &quot;./webkit/tools/layout_tests/rebaseline.py&quot;  line 190  in __init__      False)    File   &quot;/Volumes/source/chrome.git/src/webkit/tools/layout_tests/layout_package/test_expectations.  py&quot;  line 33  in __init__      is_debug_mode  is_lint_mode)    File   &quot;/Volumes/source/chrome.git/src/webkit/tools/layout_tests/layout_package/test_expectations.  py&quot;  line 261  in __init__      self._Read(self._GetIterableExpectations())    File   &quot;/Volumes/source/chrome.git/src/webkit/tools/layout_tests/layout_package/test_expectations.  py&quot;  line 540  in _Read      test_list_path  options  expectations = self.ParseExpectationsLine(line)    File   &quot;/Volumes/source/chrome.git/src/webkit/tools/layout_tests/layout_package/test_expectations.  py&quot;  line 423  in ParseExpectationsLine      self._AddError(lineno  &quot;Missing expectations.&quot;  test_and_expectation)  NameError: global name 'lineno' is not defined    Not sure if this belongs to you guys  but git blame says you were poking around in this area last. </pre>