<title>Issue 40192 -   chromium -    PyAuto crashes on linux on some machines - Project Hosting on Google Code</title> <pre> Some people on IRC have complained of pyauto crashing for them on their machines  though I hadn't seen it earlier.  The problem is due to not being able to load resources properly. I suspect that some path is not being set appropriately.    $  python chrome/test/functional/test_basic.py     Failed  [23790:23790:0401/225105:1740385573486:FATAL:app/resource_bundle_posix.cc(88)] Check failed: resources_data_. failed to   load chrome.pak  Backtrace:  	StackTrace::StackTrace() [0x7f897539ae49]  	logging::LogMessage::~LogMessage() [0x7f89753a773d]  	ResourceBundle::LoadResources() [0x7f897548a232]  	ResourceBundle::InitSharedInstance() [0x7f8975487d2f]  	ChromeTestSuite::Initialize() [0x7f897532b3e4]  	UITestSuite::Initialize() [0x7f8975351e28]  	PyUITestSuiteBase::Initialize() [0x7f897532733e]  	_wrap_PyUITestSuiteBase_Initialize [0x7f8975338262]  	0x417e33  	0x487073  	0x48a406   </pre>