Nested triggers not working properly after maximum trigger count exception is thrown    After the maximum allowed nested trigger exception is thrown  subsequent statement that result in nested trigger execution may result in the same error again even though it does not exceed the limit of nested triggers(16).e.g.:C:/derby/trunk&gt;java -classpath classes;. org.apache.derby.tools.ijij version 10.3ij&gt; connect 'jdbc:derby:wombat;create=true';ij&gt; create table t1 (i int);0 rows inserted/updated/deletedij&gt; insert into t1 values 1 2 3;3 rows inserted/updated/deletedij&gt; create trigger tr1 after update on t1 for each row update t1 set i=i+1;0 rows inserted/updated/deleted&#8211; force the 'maximum depth of nested triggers' error to occurij&gt; update t1 set i=i+1;ERROR 54038: Maximum depth of nested triggers was exceeded.ij&gt; drop trigger tr1;0 rows inserted/updated/deletedij&gt; create trigger tr1 after update on t1 referencing old as oldt for each row update t1 set i=i+1 where oldt.i=2;0 rows inserted/updated/deleted&#8211; this should have executed successfully instead of throwing the same error again!ij&gt; update t1 set i=i+1;ERROR 54038: Maximum depth of nested triggers was exceeded.ij&gt; disconnect;ij&gt; connect 'jdbc:derby:wombat';ij&gt; select * from t1;I-----------1233 rows selected&#8211; ok after reconnection  it looks like the trigger execution context(TEC) may not have been cleanup properly in the previous connectionij&gt; update t1 set i=i+1;3 rows inserted/updated/deletedij&gt; select * from t1;I-----------4563 rows selectedij&gt;   