specialCollation() and noSpecialCollation() in TableFunctionTest fail with weme6.1.    The 'specialCollation()' and 'noSpecialCollation()' fixtures in TableFunctionTest fail when run with weme6.1. I have not explicitly confirmed but it looks like this may be related to svn # 636004. The stack trace is:noSpecialCollation(o.a.dTesting.functionTests.tests.lang.TableFunctionTest)java.sql.SQLException: An attempt was made to get a data value of type 'java.lang.Object' from a data value of type 'DECIMAL'. at o.a.d.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) at o.a.d.impl.jdbc.Util.generateCsSQLException(Unknown Source) at o.a.d.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) at o.a.d.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) at o.a.d.impl.jdbc.EmbedConnection.handleException(Unknown Source) at o.a.d.impl.jdbc.ConnectionChild.handleException(Unknown Source) at o.a.d.impl.jdbc.EmbedResultSet.closeOnTransactionError(Unknown Source) at o.a.d.impl.jdbc.EmbedResultSet.movePosition(Unknown Source) at o.a.d.impl.jdbc.EmbedResultSet.next(Unknown Source) at o.a.dTesting.functionTests.tests.lang.TableFunctionTest.assertResults(TableFunctionTest.java:1935) at o.a.dTesting.functionTests.tests.lang.TableFunctionTest.assertResults(TableFunctionTest.java:1776) at o.a.dTesting.functionTests.tests.lang.TableFunctionTest.assertResults(TableFunctionTest.java:1762) at o.a.dTesting.functionTests.tests.lang.TableFunctionTest.allLegalDatatypesVTIResults(TableFunctionTest.java:1178) at o.a.dTesting.functionTests.tests.lang.TableFunctionTest.tableFunctionTest(TableFunctionTest.java:921) at o.a.dTesting.functionTests.tests.lang.TableFunctionTest.noSpecialCollation(TableFunctionTest.java:897) at java.lang.reflect.AccessibleObject.invokeV(AccessibleObject.java:205) at o.a.dTesting.junit.BaseTestCase.runBare(BaseTestCase.java:101)Caused by: ERROR 22005: An attempt was made to get a data value of type 'java.lang.Object' from a data value of type 'DECIMAL'. at o.a.d.iapi.error.StandardException.newException(Unknown Source) at o.a.d.iapi.types.DataType.dataTypeConversion(Unknown Source) at o.a.d.iapi.types.DataType.getObject(Unknown Source) at o.a.d.impl.sql.execute.VTIResultSet.cast(Unknown Source) at o.a.d.impl.sql.execute.VTIResultSet.populateFromResultSet(Unknown Source) at o.a.d.impl.sql.execute.VTIResultSet.getNextRowCore(Unknown Source) at o.a.d.impl.sql.execute.BasicNoPutResultSetImpl.getNextRow(Unknown Source)Comments from RIck on derby-dev (in response to DERBY-3341 inquiry): 'The handling of DECIMAL on the small device platform is different. The test may need some special logic so that it calls the correct method for the small device environment.'   