ASSERT FAILED calling setTransactionIsolation checking isolation_ == level   on  pooled connection    For DERBY-4314  I thought I would do a little testing to understand the server round trips in various scenarios for pooled connections. So I wrote the small attached program ConnReuse.java and hit this assertion in client:Exception in thread 'main' org.apache.derby.shared.common.sanity.AssertFailure: ASSERT FAILED at org.apache.derby.shared.common.sanity.SanityManager.ASSERT(SanityManager.java:98) at org.apache.derby.client.am.Connection.setTransactionIsolationX(Connection.java:987) at org.apache.derby.client.am.Connection.setTransactionIsolation(Connection.java:915) at org.apache.derby.client.am.LogicalConnection.setTransactionIsolation(LogicalConnection.java:253) at TestConnReuse.main(TestConnReuse.java:32)---------------To run the program on trunk:java org.apache.derby.drda.NetworkServerControl startjava TestConnReuse.This needs more investigation  but I thought I would go ahead and log the bug. I tried this only on trunk. I have not yet Tried it on the branches. Tried it with Lily's DERBY-4314 patch. Tried it with embedded. Tried actually doing something with the prior logical connection which might be related.   