10 failures and 11 errors with IBM weme6.2/j9/cdc-foundation after revision 922304 for DERBY-4483    Since March 12 there's been 10 failures and 11 errors in the nightly test run with IBM's j2ME/CDC-foundation profile implementation  see: http://people.apache.org/~myrnavl/derby_test_results/main/windows/testSummary-922467.html. Things were ok on March 10  see: http://people.apache.org/~myrnavl/derby_test_results/main/windows/testSummary-921667.html.I believe these were the effect of the following checkin for DERBY-4483:r922304 | kahatlen | 2010-03-12 08:01:20 -0800 (Fri  12 Mar 2010) | 8 linesDERBY-4483: Provide a way to change the hash algorithm used by BUILTIN authenticationI'll attach the full failure stacks in a separate file  but I believe perhaps new tests have been added that need to be excluded from the run  because the provider doesn't support the intended mechanism.I'd also be interested to know if these same failures occur with Sun's/Oracle's phoneME.This is the top of the first error:-------------------1) testVariousBuiltinAlgorithms(org.apache.derbyTesting.functionTests.tests.jdbcapi.AuthenticationTest)java.sql.SQLException: The message digest algorithm 'SHA-256' is not supported by any of the available cryptography providers. Please install a cryptography provider that supports that algorithm  or specify another algorithm in the derby.authentication.builtin.algorithm property. at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source) at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source) at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) at org.apache.derby.impl.jdbc.EmbedCallableStatement.executeStatement(Unknown Source) at org.apache.derby.impl.jdbc.EmbedPreparedStatement.execute(Unknown Source) at org.apache.derbyTesting.functionTests.tests.jdbcapi.AuthenticationTest.setDatabaseProperty(AuthenticationTest.java:1208) at org.apache.derbyTesting.functionTests.tests.jdbcapi.AuthenticationTest.setDatabaseProperty(AuthenticationTest.java:1218) at org.apache.derbyTesting.functionTests.tests.jdbcapi.AuthenticationTest.testVariousBuiltinAlgorithms(AuthenticationTest.java:1118)------------------The failures are likely a result of this - the stack shows issues like no cleaning up of databases etc.   