<title>Issue 19206 -   chromium -    binding_utils::CallFunctionInContext does not check for exceptions - Project Hosting on Google Code</title> <pre> chrome/renderer/extensions/bindings_utils.cc has a CallFunctionInContext()   function that invokes a JS function.  It is called by   EventBindings::CallFunction which is invoked from the IPC handler code in the   renderer that handles event dispatch.  The problem is that there is no   exception checking done from C++  so if an exception it thrown the javascript   execution simply terminates without any logging info available through the   inspector or on stdout/stderr.    This means if a hapless extension developer happens to cause an exception to   be thrown in the bindings JS code (say by passing arguments to an event as an   object instead of an array) then the execution simply stops without warning   at the place the exception is thrown and it's pretty much impossible to   figure out why. </pre>